name:                daily-reps
version:             1.0.0.0
github:              "jbrechtel/dailyReps"
license:             BSD3
author:              "James Brechtel"
maintainer:          "oss@james.brechtel.bike"
copyright:           "2020 James Brechtel"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/jbrechtel/daily-reps#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Werror
  - -Wall
